# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d807a59b3a362399b617a7ad2f0b69c5cb23fbd55a19981e096d15ac4f5ec049c9e114905796c7dc6fcfe2e791675082e2dd86f76b57ae3aa25c9b7a4620b2f6

test:
  secret_key_base: fd1557422f74ac8f3b2c0974d6e1747c0f8b9a305347e1237da9dc2ffb049472960b68cd08d648a59a773f59e1f9b01c6fa075b72722df3107491c8f11373c80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
